### PR TITLE
Regular expressions main structural elements with examples

### PR DESCRIPTION
**Pull request by max-prosper**

### CODE REVIEW

**Comment by 4doge** [comment]
@max-prosper please use `Other` folder for this topic, because it covers not only `Backend`. 
Please update, so we can merge. Thx.

**Comment by max-prosper** [comment]
@4doge Moved RegEx to OtHer folder and added link to it to main README

**Comment by 4doge** [comment]
@max-prosper please sort A-Z titles in `Other` in main `README.md` file.

**Comment by max-prosper** [comment]
@4doge Thanks! Will do.

**Pull request merged**
